# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_proto/transaction.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#transaction_proto/transaction.proto\x12\x0btransaction\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x63_ind\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x07 \x01(\t\"\x18\n\x16TransactionListRequest\"4\n\x1aTransactionRetrieveRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"6\n#TransactionRetrieveByAccountRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t2\x97\x04\n\x15TransactionController\x12I\n\x04List\x12#.transaction.TransactionListRequest\x1a\x18.transaction.Transaction\"\x00\x30\x01\x12>\n\x06\x43reate\x12\x18.transaction.Transaction\x1a\x18.transaction.Transaction\"\x00\x12O\n\x08Retrieve\x12\'.transaction.TransactionRetrieveRequest\x1a\x18.transaction.Transaction\"\x00\x12\x63\n\x11RetrieveByAccount\x12\x30.transaction.TransactionRetrieveByAccountRequest\x1a\x18.transaction.Transaction\"\x00\x30\x01\x12>\n\x06Update\x12\x18.transaction.Transaction\x1a\x18.transaction.Transaction\"\x00\x12=\n\x07\x44\x65stroy\x12\x18.transaction.Transaction\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\nDestroyAll\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_proto.transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTION']._serialized_start=82
  _globals['_TRANSACTION']._serialized_end=221
  _globals['_TRANSACTIONLISTREQUEST']._serialized_start=223
  _globals['_TRANSACTIONLISTREQUEST']._serialized_end=247
  _globals['_TRANSACTIONRETRIEVEREQUEST']._serialized_start=249
  _globals['_TRANSACTIONRETRIEVEREQUEST']._serialized_end=301
  _globals['_TRANSACTIONRETRIEVEBYACCOUNTREQUEST']._serialized_start=303
  _globals['_TRANSACTIONRETRIEVEBYACCOUNTREQUEST']._serialized_end=357
  _globals['_TRANSACTIONCONTROLLER']._serialized_start=360
  _globals['_TRANSACTIONCONTROLLER']._serialized_end=895
# @@protoc_insertion_point(module_scope)
