# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from transaction_proto import transaction_pb2 as transaction__proto_dot_transaction__pb2


class TransactionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/transaction.TransactionController/List',
                request_serializer=transaction__proto_dot_transaction__pb2.TransactionListRequest.SerializeToString,
                response_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                )
        self.Create = channel.unary_unary(
                '/transaction.TransactionController/Create',
                request_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
                response_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/transaction.TransactionController/Retrieve',
                request_serializer=transaction__proto_dot_transaction__pb2.TransactionRetrieveRequest.SerializeToString,
                response_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                )
        self.RetrieveByAccount = channel.unary_stream(
                '/transaction.TransactionController/RetrieveByAccount',
                request_serializer=transaction__proto_dot_transaction__pb2.TransactionRetrieveByAccountRequest.SerializeToString,
                response_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                )
        self.Update = channel.unary_unary(
                '/transaction.TransactionController/Update',
                request_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
                response_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/transaction.TransactionController/Destroy',
                request_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DestroyAll = channel.unary_unary(
                '/transaction.TransactionController/DestroyAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TransactionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveByAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=transaction__proto_dot_transaction__pb2.TransactionListRequest.FromString,
                    response_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                    response_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=transaction__proto_dot_transaction__pb2.TransactionRetrieveRequest.FromString,
                    response_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            ),
            'RetrieveByAccount': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveByAccount,
                    request_deserializer=transaction__proto_dot_transaction__pb2.TransactionRetrieveByAccountRequest.FromString,
                    response_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                    response_serializer=transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=transaction__proto_dot_transaction__pb2.Transaction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DestroyAll': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.TransactionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/transaction.TransactionController/List',
            transaction__proto_dot_transaction__pb2.TransactionListRequest.SerializeToString,
            transaction__proto_dot_transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionController/Create',
            transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            transaction__proto_dot_transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionController/Retrieve',
            transaction__proto_dot_transaction__pb2.TransactionRetrieveRequest.SerializeToString,
            transaction__proto_dot_transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveByAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/transaction.TransactionController/RetrieveByAccount',
            transaction__proto_dot_transaction__pb2.TransactionRetrieveByAccountRequest.SerializeToString,
            transaction__proto_dot_transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionController/Update',
            transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            transaction__proto_dot_transaction__pb2.Transaction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionController/Destroy',
            transaction__proto_dot_transaction__pb2.Transaction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionController/DestroyAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
