# Generated by Django 3.2.25 on 2024-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('CAD', 'CAD')], max_length=3)),
                ('customer_id', models.CharField(max_length=9)),
            ],
            options={
                'unique_together': {('customer_id', 'account_type', 'currency')},
            },
        ),
    ]
