# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_proto/account.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61\x63\x63ount_proto/account.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\"o\n\x07\x41\x63\x63ount\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x02\"\x14\n\x12\x41\x63\x63ountListRequest\"0\n\x16\x41\x63\x63ountRetrieveRequest\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\x05\"7\n AccountRetrieveByCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t2\xbd\x03\n\x11\x41\x63\x63ountController\x12\x39\n\x04List\x12\x1b.account.AccountListRequest\x1a\x10.account.Account\"\x00\x30\x01\x12.\n\x06\x43reate\x12\x10.account.Account\x1a\x10.account.Account\"\x00\x12?\n\x08Retrieve\x12\x1f.account.AccountRetrieveRequest\x1a\x10.account.Account\"\x00\x12U\n\x12RetrieveByCustomer\x12).account.AccountRetrieveByCustomerRequest\x1a\x10.account.Account\"\x00\x30\x01\x12.\n\x06Update\x12\x10.account.Account\x1a\x10.account.Account\"\x00\x12\x35\n\x07\x44\x65stroy\x12\x10.account.Account\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\nDestroyAll\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_proto.account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACCOUNT']._serialized_start=69
  _globals['_ACCOUNT']._serialized_end=180
  _globals['_ACCOUNTLISTREQUEST']._serialized_start=182
  _globals['_ACCOUNTLISTREQUEST']._serialized_end=202
  _globals['_ACCOUNTRETRIEVEREQUEST']._serialized_start=204
  _globals['_ACCOUNTRETRIEVEREQUEST']._serialized_end=252
  _globals['_ACCOUNTRETRIEVEBYCUSTOMERREQUEST']._serialized_start=254
  _globals['_ACCOUNTRETRIEVEBYCUSTOMERREQUEST']._serialized_end=309
  _globals['_ACCOUNTCONTROLLER']._serialized_start=312
  _globals['_ACCOUNTCONTROLLER']._serialized_end=757
# @@protoc_insertion_point(module_scope)
