# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_proto/customer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63ustomer_proto/customer.proto\x12\x08\x63ustomer\x1a\x1bgoogle/protobuf/empty.proto\"k\n\x08\x43ustomer\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\"\x15\n\x13\x43ustomerListRequest\".\n\x17\x43ustomerRetrieveRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\"6\n\x1e\x43ustomerRetrievebyPhoneRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t2\xcc\x03\n\x12\x43ustomerController\x12=\n\x04List\x12\x1d.customer.CustomerListRequest\x1a\x12.customer.Customer\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.customer.Customer\x1a\x12.customer.Customer\"\x00\x12\x43\n\x08Retrieve\x12!.customer.CustomerRetrieveRequest\x1a\x12.customer.Customer\"\x00\x12Q\n\x0fRetrievebyPhone\x12(.customer.CustomerRetrievebyPhoneRequest\x1a\x12.customer.Customer\"\x00\x12\x32\n\x06Update\x12\x12.customer.Customer\x1a\x12.customer.Customer\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.customer.Customer\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\nDestroyAll\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_proto.customer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMER']._serialized_start=72
  _globals['_CUSTOMER']._serialized_end=179
  _globals['_CUSTOMERLISTREQUEST']._serialized_start=181
  _globals['_CUSTOMERLISTREQUEST']._serialized_end=202
  _globals['_CUSTOMERRETRIEVEREQUEST']._serialized_start=204
  _globals['_CUSTOMERRETRIEVEREQUEST']._serialized_end=250
  _globals['_CUSTOMERRETRIEVEBYPHONEREQUEST']._serialized_start=252
  _globals['_CUSTOMERRETRIEVEBYPHONEREQUEST']._serialized_end=306
  _globals['_CUSTOMERCONTROLLER']._serialized_start=309
  _globals['_CUSTOMERCONTROLLER']._serialized_end=769
# @@protoc_insertion_point(module_scope)
